- name: Tencent CloudBase Github Action
  # You may pin to the exact commit or the version.
  # uses: TencentCloudBase/cloudbase-action@a6f4e1491453f02f05f0df92337d4999a4e51c18
  uses: TencentCloudBase/cloudbase-action@v2
  with:
    # 云开发 secretId
    secretId: AKIDUu8C7pMhoiPsAKVakpkU1LRJxRlvteCX
    # 云开发 secretKey
    secretKey: A7qMfkcGk3B6mESRCj160jFahaLtFOL6
    # 云开发环境 Id
    envId: 1300294727